Add application app
lujorryn/PetPal-G0346 pull request #13
Opened 2023-11-11 15:37 UTC by JuneOh710

2023-11-11 19:32 UTC, iamyanbo requested changes

2023-11-11 19:32 UTC, iamyanbo commented on petpal/applications/views.py
> +        return JsonResponse({'data': serialized_apps.data}, status=status.HTTP_200_OK)
change to return paginator.get_paginated_response({'data': serialized_apps.data}) instead of JsonResponse to actually show pages

2023-11-11 19:32 UTC, iamyanbo commented on petpal/applications/views.py
> +        listing = PetListing.objects.get(pk=pet_id)
Catch if pet_id out of range

2023-11-11 19:33 UTC, iamyanbo commented
Also application should create a new notification, and depending on the receiving user's settings of is_notif include them in the relation

2023-11-11 19:38 UTC, iamyanbo requested changes

2023-11-11 19:38 UTC, iamyanbo commented on petpal/applications/views.py
> +        app = Application.objects.get(pk=app_id)
Catch if app_id is out of range. Also only users that have access to the specific application should be able to view

2023-11-11 23:28 UTC, JuneOh710 commented on petpal/applications/views.py
> +        listing = PetListing.objects.get(pk=pet_id)
good 'catch' ha-ha

2023-11-12 16:46 UTC, iamyanbo requested changes

2023-11-12 16:46 UTC, iamyanbo commented on petpal/applications/views.py
> +        put_app = Application.objects.get(pk=app_id)
try catch this

2023-11-12 16:46 UTC, iamyanbo commented on petpal/applications/views.py
> +        if put_app.seeker.is_notif_status:
The logic to add recipients to the notification should be different, if a user updated, it should send to shelter, and if shelter updated, it should send to user

2023-11-12 16:46 UTC, iamyanbo commented on petpal/applications/views.py
> +        if put_app.seeker.is_notif_status:
Otherwise looks good

2023-11-12 22:36 UTC, iamyanbo approved these changes

2023-11-12 23:27 UTC, merged